# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 053448cca8eaffd902684698074a324e8d29d9cfec3ad6af07924e46f22291b7b5f00ee4c260ab6116a7fd1cd681d59bf0dc4f5aba9f54dc26140684a57b1458

test:
  secret_key_base: 01754be4a1b35909bfbb9f473eee9af3288ba7262bce77a95f64c8c62d804aea4f2a72e8c62f548d2a4b9d0b7a5665b5f881b2b2c04d809f47f8dd9619252c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
